# Generated by Django 6.0 on 2025-12-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('annual_fee_adult', models.PositiveIntegerField()),
                ('annual_fee_child', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('cpr', models.CharField(help_text='Format: xxyyzz-zzzz', max_length=11, unique=True)),
                ('birth_date', models.DateField()),
                ('is_passive', models.BooleanField(default=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('num_children_in_gif', models.PositiveIntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.household')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_board_member', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_memberships', to='members.member')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='members.sport')),
            ],
            options={
                'unique_together': {('member', 'sport')},
            },
        ),
    ]
